### ISSUE TITLE
The PyAOS census

### ISSUE THREAD

**Issue by DamienIrving** [PyAOS/pyaos.github.io#3]
In order to keep the content on the [PyAOS website](https://pyaos.github.io/) as up-to-date and relevant as possible, it would be useful to conduct a regular census (perhaps every year or two).

I'm thinking that the data (which would be made openly available in csv format at this GitHub repository) could be collected using Google Forms. 

Here's what I'm thinking for questions:

(Multiple choice means you can only pick one of the options; checkbox means you can select as many as you like.) 

### Demographics

| Question | Type | Options |
| ---           | ---          | ---        |
| Age | Free text |  |
| Gender: How do you identify? | Multiple choice | - Woman <br> - Non-binary <br> - Man <br> - Other (free text) | 
| Career stage | Multiple choice | - Undergraduate <br> - Masters <br> - PhD <br> - Academic (within 5 years of highest qualification) <br> - Academic (more than 5 years post highest qualification) <br> - Industry / Professional (within 5 years) <br> - Industry / Professional (more than 5 years) <br> - Other (free text) |
| AOS discipline/s | Checkbox | - Atmospheric Aerosols <br> - Atmospheric Chemistry <br> - Atmospheric Dynamics <br> - Atmospheric Radiation <br> - Climate Change Processes <br> - Climatology (excl. Climate Change Processes) <br> - Cloud Physics <br> - Meteorology <br> - Biological Oceanography <br> - Chemical Oceanography <br> - Physical Oceanography <br> - Paleoclimatology <br> - Tropospheric and Stratospheric Physics <br> - Modelling <br> - AOS Research Software Engineer <br> - AOS Research Computing Support <br> - Other (free text) | 
| Country of residence | Free text | Use 2-letter country code from [this list](https://www.iban.com/country-codes) |
| How long have you been using Python? | Multiple choice | - less than 1 year <br> - 1-2 years <br> - 2-5 years <br> - 6-10 years <br> - more than 10 years |
| What types of AOS data do you work with? | Checkbox | - Raster (i.e. multi-dimensional gridded data such as a regular time/latitude/longitude/depth grid) <br> - Vector (i.e. discrete geometric locations that define the shape of a spatial point, line or polygon) <br> - Tabular <br> - Other (free text) |
| Which of those data types do you most commonly work with? | Multiple choice | - Raster (i.e. multi-dimensional gridded data such as a regular time/latitude/longitude/depth grid) <br> - Vector (i.e. discrete geometric locations that define the shape of a spatial point, line or polygon) <br> - Tabular <br> - Other (free text) |   
| What file formats are your AOS data stored in? | Checkbox | - netCDF <br> - Zarr <br> - GRIB <br> - HDF <br> - GeoTIFF <br> - csv <br> - GeoJSON <br> - GeoPackage <br> - Shapefile <br> - MapInfo TAB <br> - ESRI File Geodatabase <br> - A custom binary format <br> - Other (free text) | 
| Which of those file formats do you most commonly work with? | Multiple choice | - netCDF <br> - Zarr <br> - GRIB <br> - HDF <br> - GeoTIFF <br> - csv <br> - GeoJSON <br> - GeoPackage <br> - Shapefile <br> - MapInfo TAB <br> - ESRI File Geodatabase <br> - A custom binary format <br> - Other (free text) | 
| What computing platforms do you use for your AOS data science? | Checkbox | - Personal laptop/desktop <br> - Supercomputer (e.g. run by your institution or a national facility) <br> - Cloud (e.g. Amazon Web Services) <br> - Other (free text) |
| Which of those computing platforms do you most commonly work on for your AOS data sciecne? | Multiple choice | - Personal laptop/desktop <br> - Supercomputer (e.g. run by your institution or a national facility) <br> - Cloud (e.g. Amazon Web Services) <br> - Other (free text) |
| What development environments do you regularly use for your Python coding? | Checkbox | - Jupyter <br> - PyCharm <br> - Spyder <br> - Notepad++ <br> - Sublime Text <br> - Vim <br> - Other (free text) |

### Main question (free text)

Writing Python code typically begins with importing various libraries that are either part of the Python standard library or that you've installed using the Python package installer (pip) or conda. Take a look back over five Python scripts / notebooks that you've written recently for AOS data science tasks and cut and paste below all the `import` statements that you used in those scripts / notebooks (please remove any duplicates). For example, your list might look something like:
```
import sys
import os
import argparse
import numpy as np
import xarray as xr
import iris
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import pyart
```
If you've imported any of your own modules, please include the libraries imported in those modules in your list too.

Are there any PyAOS libraries that aren't on your list from the last couple of months but that you've used previously and would like to highlight?

**Comment by DamienIrving** [comment]
If anyone has any feedback on those proposed questions (or the idea of a census in general) please feel free to comment on this issue thread.

**Comment by fmaussion** [comment]
Looks great thanks! minor comments:

- `How long have you been using Python?` -> only one option possible
- `What type of AOS data do you most commonly work with?` -> I would personally tick all the boxes and I think many of us will
- `What file format is your AOS data typically stored in?` -> this list does not entail any vector format, somewhat contradicting the question above

**Comment by tjlang** [comment]
Nice survey overall. Add "atmospheric electricity/lightning" to discipline list. I would do a dropdown list of countries rather than force people to look it up themselves. Most websites do that. Need HDF and Grib in the data format list. Might also consider changing CSV to "CSV, ICARTT, or other ASCII." There are also a lot of custom binary formats used in the field (think Level 0 raw instrument data), so might want that as another format option. Development environment answers need Xcode (Mac). I am not sure the "type of AOS data" question is going to be very useful. Anybody worth their salt works with all types of data and will want to check all of the above.

**Comment by davidedelvento** [comment]
I would make the "AOS discipline/s" multiple choices rather than checkbox. Or perhaps even better make if checkbox for "primary" and make an identical question for "secondary" with the multiple choice.

UPDATE:
Perhaps I misunderstood what you meant by "Multiple Choice" otherwise the "How long have you been using Python?" does not make sense. If by "Multiple Choice" you mean https://en.wikipedia.org/wiki/Radio_button and by checkbox you mean https://en.wikipedia.org/wiki/Checkbox then it's good as is -- still remains if you want to separate the primary (radiobutton) from secondary (checkbox)

**Comment by davidedelvento** [comment]
Separate "AOS Research Software Engineer / Research Computing Support " in two since these are separate in my opinion (I do both, but much more of the latter than the former)

**Comment by dopplershift** [comment]
The definitions of Vector vs. Raster data seemed flipped from what they should be?

**Comment by soto97** [comment]
I think you should word questions 5, 6, and 7 exactly the same, and emphasize that the goal of these questions is not to capture all of the options but the number 1 used option (at least, I assume that's the goal). For example, in question 6, "What file format is your AOS data typically stored in?", I think you are trying to figure out the primary format used by the PyAOS community (hence the use of multiple choice, which, ironically, allows only one choice among many choices). Like @tjlang I use all of the options, but if you want my most frequently used file format, it's NetCDF. So we need to figure out some wording to make this obvious to the poll takers.

For question 6, "What file format is your AOS data typically stored in?" I agree that you should add HDF and Grib as options.

I am glad that you added the "Other (free text)" option. Since this is a first demographic survey (I think it's the first) we really don't know what the dominant answers will be. The "Other (free text)" will help deal with any false assumptions.

Finally, besides career stage (question 1) and Python knowledge stage (question 4), should we also collect data on actual age* and on gender? Would that be of some value to the community? 

*Career stage doesn't always map to age. For example, I was in grad school in my 30s, which is not, I think,  typical and wouldn't be what is normally inferred from the career stage information.

Finally, thanks for doing this. I think it's a great idea.

**Comment by DamienIrving** [comment]
>     * `What file format is your AOS data typically stored in?` -> this list does not entail any vector format, somewhat contradicting the question above

Good point, @fmaussion. What are the most common AOS vector formats?

**Comment by DamienIrving** [comment]
Thanks, everyone! I've incorporated most of your suggestions and will hopefully send out the survey later this week :smile:

**Comment by fmaussion** [comment]
> What are the most common AOS vector formats?

The only one I know is the Esri shapefile format!

**Comment by DamienIrving** [comment]
The census is now live at: https://forms.gle/L84W7bsxmP86G3Ji9
